server:
  port: 8080
  shutdown: graceful

spring:
  application:
    name: chat-service
  data:
    mongodb:
      auto-index-creation: true
      uri: mongodb://admin:admin@localhost:27017/chatmessagesdb?authSource=admin